/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AuthedAnalisisAnalisisRouteImport } from './routes/_authed/analisis/analisis'
import { Route as AuthedAnalisisCantidadesRouteImport } from './routes/_authed/analisis/cantidades'
import { Route as AuthedParametrosCategoriasRouteImport } from './routes/_authed/parametros/categorias'
import { Route as AuthedParametrosMaterialesRouteImport } from './routes/_authed/parametros/materiales'
import { Route as AuthedParametrosPartidasRouteImport } from './routes/_authed/parametros/partidas'
import { Route as AuthedParametrosProveedoresRouteImport } from './routes/_authed/parametros/proveedores'
import { Route as AuthedReportesActualRouteImport } from './routes/_authed/reportes/actual'
import { Route as AuthedReportesCuadreRouteImport } from './routes/_authed/reportes/cuadre'
import { Route as AuthedReportesGastadoPorPartidaRouteImport } from './routes/_authed/reportes/gastado-por-partida'
import { Route as AuthedReportesHistoricoRouteImport } from './routes/_authed/reportes/historico'
import { Route as AuthedTransaccionesCierreRouteImport } from './routes/_authed/transacciones/cierre'
import { Route as AuthedTransaccionesPresupuestoRouteImport } from './routes/_authed/transacciones/presupuesto'
import { Route as AuthedUsuariosAdminRouteImport } from './routes/_authed/usuarios/admin'
import { Route as AuthedUsuariosPerfilRouteImport } from './routes/_authed/usuarios/perfil'
import { Route as AuthedParametrosProyectosIndexRouteImport } from './routes/_authed/parametros/proyectos/index'
import { Route as AuthedParametrosProyectosProyectoIdRouteImport } from './routes/_authed/parametros/proyectos/$proyectoId'
import { Route as AuthedParametrosProyectosCrearRouteImport } from './routes/_authed/parametros/proyectos/crear'
import { Route as AuthedParametrosRubrosIndexRouteImport } from './routes/_authed/parametros/rubros/index'
import { Route as AuthedParametrosRubrosRubroIdRouteImport } from './routes/_authed/parametros/rubros/$rubroId'
import { Route as AuthedParametrosRubrosCrearRouteImport } from './routes/_authed/parametros/rubros/crear'
import { Route as AuthedTransaccionesFacturaIndexRouteImport } from './routes/_authed/transacciones/factura/index'
import { Route as AuthedTransaccionesFacturaFacturaIdRouteImport } from './routes/_authed/transacciones/factura/$facturaId'
import { Route as AuthedTransaccionesFacturaCrearRouteImport } from './routes/_authed/transacciones/factura/crear'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAnalisisAnalisisRoute = AuthedAnalisisAnalisisRouteImport.update({
  id: '/analisis/analisis',
  path: '/analisis/analisis',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAnalisisCantidadesRoute =
  AuthedAnalisisCantidadesRouteImport.update({
    id: '/analisis/cantidades',
    path: '/analisis/cantidades',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedParametrosCategoriasRoute =
  AuthedParametrosCategoriasRouteImport.update({
    id: '/parametros/categorias',
    path: '/parametros/categorias',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedParametrosMaterialesRoute =
  AuthedParametrosMaterialesRouteImport.update({
    id: '/parametros/materiales',
    path: '/parametros/materiales',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedParametrosPartidasRoute =
  AuthedParametrosPartidasRouteImport.update({
    id: '/parametros/partidas',
    path: '/parametros/partidas',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedParametrosProveedoresRoute =
  AuthedParametrosProveedoresRouteImport.update({
    id: '/parametros/proveedores',
    path: '/parametros/proveedores',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedReportesActualRoute = AuthedReportesActualRouteImport.update({
  id: '/reportes/actual',
  path: '/reportes/actual',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedReportesCuadreRoute = AuthedReportesCuadreRouteImport.update({
  id: '/reportes/cuadre',
  path: '/reportes/cuadre',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedReportesGastadoPorPartidaRoute =
  AuthedReportesGastadoPorPartidaRouteImport.update({
    id: '/reportes/gastado-por-partida',
    path: '/reportes/gastado-por-partida',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedReportesHistoricoRoute = AuthedReportesHistoricoRouteImport.update({
  id: '/reportes/historico',
  path: '/reportes/historico',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTransaccionesCierreRoute =
  AuthedTransaccionesCierreRouteImport.update({
    id: '/transacciones/cierre',
    path: '/transacciones/cierre',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedTransaccionesPresupuestoRoute =
  AuthedTransaccionesPresupuestoRouteImport.update({
    id: '/transacciones/presupuesto',
    path: '/transacciones/presupuesto',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedUsuariosAdminRoute = AuthedUsuariosAdminRouteImport.update({
  id: '/usuarios/admin',
  path: '/usuarios/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedUsuariosPerfilRoute = AuthedUsuariosPerfilRouteImport.update({
  id: '/usuarios/perfil',
  path: '/usuarios/perfil',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedParametrosProyectosIndexRoute =
  AuthedParametrosProyectosIndexRouteImport.update({
    id: '/parametros/proyectos/',
    path: '/parametros/proyectos/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedParametrosProyectosProyectoIdRoute =
  AuthedParametrosProyectosProyectoIdRouteImport.update({
    id: '/parametros/proyectos/$proyectoId',
    path: '/parametros/proyectos/$proyectoId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedParametrosProyectosCrearRoute =
  AuthedParametrosProyectosCrearRouteImport.update({
    id: '/parametros/proyectos/crear',
    path: '/parametros/proyectos/crear',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedParametrosRubrosIndexRoute =
  AuthedParametrosRubrosIndexRouteImport.update({
    id: '/parametros/rubros/',
    path: '/parametros/rubros/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedParametrosRubrosRubroIdRoute =
  AuthedParametrosRubrosRubroIdRouteImport.update({
    id: '/parametros/rubros/$rubroId',
    path: '/parametros/rubros/$rubroId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedParametrosRubrosCrearRoute =
  AuthedParametrosRubrosCrearRouteImport.update({
    id: '/parametros/rubros/crear',
    path: '/parametros/rubros/crear',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedTransaccionesFacturaIndexRoute =
  AuthedTransaccionesFacturaIndexRouteImport.update({
    id: '/transacciones/factura/',
    path: '/transacciones/factura/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedTransaccionesFacturaFacturaIdRoute =
  AuthedTransaccionesFacturaFacturaIdRouteImport.update({
    id: '/transacciones/factura/$facturaId',
    path: '/transacciones/factura/$facturaId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedTransaccionesFacturaCrearRoute =
  AuthedTransaccionesFacturaCrearRouteImport.update({
    id: '/transacciones/factura/crear',
    path: '/transacciones/factura/crear',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/analisis/analisis': typeof AuthedAnalisisAnalisisRoute
  '/analisis/cantidades': typeof AuthedAnalisisCantidadesRoute
  '/parametros/categorias': typeof AuthedParametrosCategoriasRoute
  '/parametros/materiales': typeof AuthedParametrosMaterialesRoute
  '/parametros/partidas': typeof AuthedParametrosPartidasRoute
  '/parametros/proveedores': typeof AuthedParametrosProveedoresRoute
  '/reportes/actual': typeof AuthedReportesActualRoute
  '/reportes/cuadre': typeof AuthedReportesCuadreRoute
  '/reportes/gastado-por-partida': typeof AuthedReportesGastadoPorPartidaRoute
  '/reportes/historico': typeof AuthedReportesHistoricoRoute
  '/transacciones/cierre': typeof AuthedTransaccionesCierreRoute
  '/transacciones/presupuesto': typeof AuthedTransaccionesPresupuestoRoute
  '/usuarios/admin': typeof AuthedUsuariosAdminRoute
  '/usuarios/perfil': typeof AuthedUsuariosPerfilRoute
  '/parametros/proyectos/$proyectoId': typeof AuthedParametrosProyectosProyectoIdRoute
  '/parametros/proyectos/crear': typeof AuthedParametrosProyectosCrearRoute
  '/parametros/rubros/$rubroId': typeof AuthedParametrosRubrosRubroIdRoute
  '/parametros/rubros/crear': typeof AuthedParametrosRubrosCrearRoute
  '/transacciones/factura/$facturaId': typeof AuthedTransaccionesFacturaFacturaIdRoute
  '/transacciones/factura/crear': typeof AuthedTransaccionesFacturaCrearRoute
  '/parametros/proyectos/': typeof AuthedParametrosProyectosIndexRoute
  '/parametros/rubros/': typeof AuthedParametrosRubrosIndexRoute
  '/transacciones/factura/': typeof AuthedTransaccionesFacturaIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/': typeof AuthedIndexRoute
  '/analisis/analisis': typeof AuthedAnalisisAnalisisRoute
  '/analisis/cantidades': typeof AuthedAnalisisCantidadesRoute
  '/parametros/categorias': typeof AuthedParametrosCategoriasRoute
  '/parametros/materiales': typeof AuthedParametrosMaterialesRoute
  '/parametros/partidas': typeof AuthedParametrosPartidasRoute
  '/parametros/proveedores': typeof AuthedParametrosProveedoresRoute
  '/reportes/actual': typeof AuthedReportesActualRoute
  '/reportes/cuadre': typeof AuthedReportesCuadreRoute
  '/reportes/gastado-por-partida': typeof AuthedReportesGastadoPorPartidaRoute
  '/reportes/historico': typeof AuthedReportesHistoricoRoute
  '/transacciones/cierre': typeof AuthedTransaccionesCierreRoute
  '/transacciones/presupuesto': typeof AuthedTransaccionesPresupuestoRoute
  '/usuarios/admin': typeof AuthedUsuariosAdminRoute
  '/usuarios/perfil': typeof AuthedUsuariosPerfilRoute
  '/parametros/proyectos/$proyectoId': typeof AuthedParametrosProyectosProyectoIdRoute
  '/parametros/proyectos/crear': typeof AuthedParametrosProyectosCrearRoute
  '/parametros/rubros/$rubroId': typeof AuthedParametrosRubrosRubroIdRoute
  '/parametros/rubros/crear': typeof AuthedParametrosRubrosCrearRoute
  '/transacciones/factura/$facturaId': typeof AuthedTransaccionesFacturaFacturaIdRoute
  '/transacciones/factura/crear': typeof AuthedTransaccionesFacturaCrearRoute
  '/parametros/proyectos': typeof AuthedParametrosProyectosIndexRoute
  '/parametros/rubros': typeof AuthedParametrosRubrosIndexRoute
  '/transacciones/factura': typeof AuthedTransaccionesFacturaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/analisis/analisis': typeof AuthedAnalisisAnalisisRoute
  '/_authed/analisis/cantidades': typeof AuthedAnalisisCantidadesRoute
  '/_authed/parametros/categorias': typeof AuthedParametrosCategoriasRoute
  '/_authed/parametros/materiales': typeof AuthedParametrosMaterialesRoute
  '/_authed/parametros/partidas': typeof AuthedParametrosPartidasRoute
  '/_authed/parametros/proveedores': typeof AuthedParametrosProveedoresRoute
  '/_authed/reportes/actual': typeof AuthedReportesActualRoute
  '/_authed/reportes/cuadre': typeof AuthedReportesCuadreRoute
  '/_authed/reportes/gastado-por-partida': typeof AuthedReportesGastadoPorPartidaRoute
  '/_authed/reportes/historico': typeof AuthedReportesHistoricoRoute
  '/_authed/transacciones/cierre': typeof AuthedTransaccionesCierreRoute
  '/_authed/transacciones/presupuesto': typeof AuthedTransaccionesPresupuestoRoute
  '/_authed/usuarios/admin': typeof AuthedUsuariosAdminRoute
  '/_authed/usuarios/perfil': typeof AuthedUsuariosPerfilRoute
  '/_authed/parametros/proyectos/$proyectoId': typeof AuthedParametrosProyectosProyectoIdRoute
  '/_authed/parametros/proyectos/crear': typeof AuthedParametrosProyectosCrearRoute
  '/_authed/parametros/rubros/$rubroId': typeof AuthedParametrosRubrosRubroIdRoute
  '/_authed/parametros/rubros/crear': typeof AuthedParametrosRubrosCrearRoute
  '/_authed/transacciones/factura/$facturaId': typeof AuthedTransaccionesFacturaFacturaIdRoute
  '/_authed/transacciones/factura/crear': typeof AuthedTransaccionesFacturaCrearRoute
  '/_authed/parametros/proyectos/': typeof AuthedParametrosProyectosIndexRoute
  '/_authed/parametros/rubros/': typeof AuthedParametrosRubrosIndexRoute
  '/_authed/transacciones/factura/': typeof AuthedTransaccionesFacturaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/uploadthing'
    | '/analisis/analisis'
    | '/analisis/cantidades'
    | '/parametros/categorias'
    | '/parametros/materiales'
    | '/parametros/partidas'
    | '/parametros/proveedores'
    | '/reportes/actual'
    | '/reportes/cuadre'
    | '/reportes/gastado-por-partida'
    | '/reportes/historico'
    | '/transacciones/cierre'
    | '/transacciones/presupuesto'
    | '/usuarios/admin'
    | '/usuarios/perfil'
    | '/parametros/proyectos/$proyectoId'
    | '/parametros/proyectos/crear'
    | '/parametros/rubros/$rubroId'
    | '/parametros/rubros/crear'
    | '/transacciones/factura/$facturaId'
    | '/transacciones/factura/crear'
    | '/parametros/proyectos/'
    | '/parametros/rubros/'
    | '/transacciones/factura/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/uploadthing'
    | '/'
    | '/analisis/analisis'
    | '/analisis/cantidades'
    | '/parametros/categorias'
    | '/parametros/materiales'
    | '/parametros/partidas'
    | '/parametros/proveedores'
    | '/reportes/actual'
    | '/reportes/cuadre'
    | '/reportes/gastado-por-partida'
    | '/reportes/historico'
    | '/transacciones/cierre'
    | '/transacciones/presupuesto'
    | '/usuarios/admin'
    | '/usuarios/perfil'
    | '/parametros/proyectos/$proyectoId'
    | '/parametros/proyectos/crear'
    | '/parametros/rubros/$rubroId'
    | '/parametros/rubros/crear'
    | '/transacciones/factura/$facturaId'
    | '/transacciones/factura/crear'
    | '/parametros/proyectos'
    | '/parametros/rubros'
    | '/transacciones/factura'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/api/uploadthing'
    | '/_authed/'
    | '/_authed/analisis/analisis'
    | '/_authed/analisis/cantidades'
    | '/_authed/parametros/categorias'
    | '/_authed/parametros/materiales'
    | '/_authed/parametros/partidas'
    | '/_authed/parametros/proveedores'
    | '/_authed/reportes/actual'
    | '/_authed/reportes/cuadre'
    | '/_authed/reportes/gastado-por-partida'
    | '/_authed/reportes/historico'
    | '/_authed/transacciones/cierre'
    | '/_authed/transacciones/presupuesto'
    | '/_authed/usuarios/admin'
    | '/_authed/usuarios/perfil'
    | '/_authed/parametros/proyectos/$proyectoId'
    | '/_authed/parametros/proyectos/crear'
    | '/_authed/parametros/rubros/$rubroId'
    | '/_authed/parametros/rubros/crear'
    | '/_authed/transacciones/factura/$facturaId'
    | '/_authed/transacciones/factura/crear'
    | '/_authed/parametros/proyectos/'
    | '/_authed/parametros/rubros/'
    | '/_authed/transacciones/factura/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/analisis/analisis': {
      id: '/_authed/analisis/analisis'
      path: '/analisis/analisis'
      fullPath: '/analisis/analisis'
      preLoaderRoute: typeof AuthedAnalisisAnalisisRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/analisis/cantidades': {
      id: '/_authed/analisis/cantidades'
      path: '/analisis/cantidades'
      fullPath: '/analisis/cantidades'
      preLoaderRoute: typeof AuthedAnalisisCantidadesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/categorias': {
      id: '/_authed/parametros/categorias'
      path: '/parametros/categorias'
      fullPath: '/parametros/categorias'
      preLoaderRoute: typeof AuthedParametrosCategoriasRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/materiales': {
      id: '/_authed/parametros/materiales'
      path: '/parametros/materiales'
      fullPath: '/parametros/materiales'
      preLoaderRoute: typeof AuthedParametrosMaterialesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/partidas': {
      id: '/_authed/parametros/partidas'
      path: '/parametros/partidas'
      fullPath: '/parametros/partidas'
      preLoaderRoute: typeof AuthedParametrosPartidasRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/proveedores': {
      id: '/_authed/parametros/proveedores'
      path: '/parametros/proveedores'
      fullPath: '/parametros/proveedores'
      preLoaderRoute: typeof AuthedParametrosProveedoresRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/reportes/actual': {
      id: '/_authed/reportes/actual'
      path: '/reportes/actual'
      fullPath: '/reportes/actual'
      preLoaderRoute: typeof AuthedReportesActualRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/reportes/cuadre': {
      id: '/_authed/reportes/cuadre'
      path: '/reportes/cuadre'
      fullPath: '/reportes/cuadre'
      preLoaderRoute: typeof AuthedReportesCuadreRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/reportes/gastado-por-partida': {
      id: '/_authed/reportes/gastado-por-partida'
      path: '/reportes/gastado-por-partida'
      fullPath: '/reportes/gastado-por-partida'
      preLoaderRoute: typeof AuthedReportesGastadoPorPartidaRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/reportes/historico': {
      id: '/_authed/reportes/historico'
      path: '/reportes/historico'
      fullPath: '/reportes/historico'
      preLoaderRoute: typeof AuthedReportesHistoricoRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/transacciones/cierre': {
      id: '/_authed/transacciones/cierre'
      path: '/transacciones/cierre'
      fullPath: '/transacciones/cierre'
      preLoaderRoute: typeof AuthedTransaccionesCierreRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/transacciones/presupuesto': {
      id: '/_authed/transacciones/presupuesto'
      path: '/transacciones/presupuesto'
      fullPath: '/transacciones/presupuesto'
      preLoaderRoute: typeof AuthedTransaccionesPresupuestoRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/usuarios/admin': {
      id: '/_authed/usuarios/admin'
      path: '/usuarios/admin'
      fullPath: '/usuarios/admin'
      preLoaderRoute: typeof AuthedUsuariosAdminRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/usuarios/perfil': {
      id: '/_authed/usuarios/perfil'
      path: '/usuarios/perfil'
      fullPath: '/usuarios/perfil'
      preLoaderRoute: typeof AuthedUsuariosPerfilRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/proyectos/': {
      id: '/_authed/parametros/proyectos/'
      path: '/parametros/proyectos'
      fullPath: '/parametros/proyectos/'
      preLoaderRoute: typeof AuthedParametrosProyectosIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/proyectos/$proyectoId': {
      id: '/_authed/parametros/proyectos/$proyectoId'
      path: '/parametros/proyectos/$proyectoId'
      fullPath: '/parametros/proyectos/$proyectoId'
      preLoaderRoute: typeof AuthedParametrosProyectosProyectoIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/proyectos/crear': {
      id: '/_authed/parametros/proyectos/crear'
      path: '/parametros/proyectos/crear'
      fullPath: '/parametros/proyectos/crear'
      preLoaderRoute: typeof AuthedParametrosProyectosCrearRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/rubros/': {
      id: '/_authed/parametros/rubros/'
      path: '/parametros/rubros'
      fullPath: '/parametros/rubros/'
      preLoaderRoute: typeof AuthedParametrosRubrosIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/rubros/$rubroId': {
      id: '/_authed/parametros/rubros/$rubroId'
      path: '/parametros/rubros/$rubroId'
      fullPath: '/parametros/rubros/$rubroId'
      preLoaderRoute: typeof AuthedParametrosRubrosRubroIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parametros/rubros/crear': {
      id: '/_authed/parametros/rubros/crear'
      path: '/parametros/rubros/crear'
      fullPath: '/parametros/rubros/crear'
      preLoaderRoute: typeof AuthedParametrosRubrosCrearRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/transacciones/factura/': {
      id: '/_authed/transacciones/factura/'
      path: '/transacciones/factura'
      fullPath: '/transacciones/factura/'
      preLoaderRoute: typeof AuthedTransaccionesFacturaIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/transacciones/factura/$facturaId': {
      id: '/_authed/transacciones/factura/$facturaId'
      path: '/transacciones/factura/$facturaId'
      fullPath: '/transacciones/factura/$facturaId'
      preLoaderRoute: typeof AuthedTransaccionesFacturaFacturaIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/transacciones/factura/crear': {
      id: '/_authed/transacciones/factura/crear'
      path: '/transacciones/factura/crear'
      fullPath: '/transacciones/factura/crear'
      preLoaderRoute: typeof AuthedTransaccionesFacturaCrearRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAnalisisAnalisisRoute: typeof AuthedAnalisisAnalisisRoute
  AuthedAnalisisCantidadesRoute: typeof AuthedAnalisisCantidadesRoute
  AuthedParametrosCategoriasRoute: typeof AuthedParametrosCategoriasRoute
  AuthedParametrosMaterialesRoute: typeof AuthedParametrosMaterialesRoute
  AuthedParametrosPartidasRoute: typeof AuthedParametrosPartidasRoute
  AuthedParametrosProveedoresRoute: typeof AuthedParametrosProveedoresRoute
  AuthedReportesActualRoute: typeof AuthedReportesActualRoute
  AuthedReportesCuadreRoute: typeof AuthedReportesCuadreRoute
  AuthedReportesGastadoPorPartidaRoute: typeof AuthedReportesGastadoPorPartidaRoute
  AuthedReportesHistoricoRoute: typeof AuthedReportesHistoricoRoute
  AuthedTransaccionesCierreRoute: typeof AuthedTransaccionesCierreRoute
  AuthedTransaccionesPresupuestoRoute: typeof AuthedTransaccionesPresupuestoRoute
  AuthedUsuariosAdminRoute: typeof AuthedUsuariosAdminRoute
  AuthedUsuariosPerfilRoute: typeof AuthedUsuariosPerfilRoute
  AuthedParametrosProyectosProyectoIdRoute: typeof AuthedParametrosProyectosProyectoIdRoute
  AuthedParametrosProyectosCrearRoute: typeof AuthedParametrosProyectosCrearRoute
  AuthedParametrosRubrosRubroIdRoute: typeof AuthedParametrosRubrosRubroIdRoute
  AuthedParametrosRubrosCrearRoute: typeof AuthedParametrosRubrosCrearRoute
  AuthedTransaccionesFacturaFacturaIdRoute: typeof AuthedTransaccionesFacturaFacturaIdRoute
  AuthedTransaccionesFacturaCrearRoute: typeof AuthedTransaccionesFacturaCrearRoute
  AuthedParametrosProyectosIndexRoute: typeof AuthedParametrosProyectosIndexRoute
  AuthedParametrosRubrosIndexRoute: typeof AuthedParametrosRubrosIndexRoute
  AuthedTransaccionesFacturaIndexRoute: typeof AuthedTransaccionesFacturaIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAnalisisAnalisisRoute: AuthedAnalisisAnalisisRoute,
  AuthedAnalisisCantidadesRoute: AuthedAnalisisCantidadesRoute,
  AuthedParametrosCategoriasRoute: AuthedParametrosCategoriasRoute,
  AuthedParametrosMaterialesRoute: AuthedParametrosMaterialesRoute,
  AuthedParametrosPartidasRoute: AuthedParametrosPartidasRoute,
  AuthedParametrosProveedoresRoute: AuthedParametrosProveedoresRoute,
  AuthedReportesActualRoute: AuthedReportesActualRoute,
  AuthedReportesCuadreRoute: AuthedReportesCuadreRoute,
  AuthedReportesGastadoPorPartidaRoute: AuthedReportesGastadoPorPartidaRoute,
  AuthedReportesHistoricoRoute: AuthedReportesHistoricoRoute,
  AuthedTransaccionesCierreRoute: AuthedTransaccionesCierreRoute,
  AuthedTransaccionesPresupuestoRoute: AuthedTransaccionesPresupuestoRoute,
  AuthedUsuariosAdminRoute: AuthedUsuariosAdminRoute,
  AuthedUsuariosPerfilRoute: AuthedUsuariosPerfilRoute,
  AuthedParametrosProyectosProyectoIdRoute:
    AuthedParametrosProyectosProyectoIdRoute,
  AuthedParametrosProyectosCrearRoute: AuthedParametrosProyectosCrearRoute,
  AuthedParametrosRubrosRubroIdRoute: AuthedParametrosRubrosRubroIdRoute,
  AuthedParametrosRubrosCrearRoute: AuthedParametrosRubrosCrearRoute,
  AuthedTransaccionesFacturaFacturaIdRoute:
    AuthedTransaccionesFacturaFacturaIdRoute,
  AuthedTransaccionesFacturaCrearRoute: AuthedTransaccionesFacturaCrearRoute,
  AuthedParametrosProyectosIndexRoute: AuthedParametrosProyectosIndexRoute,
  AuthedParametrosRubrosIndexRoute: AuthedParametrosRubrosIndexRoute,
  AuthedTransaccionesFacturaIndexRoute: AuthedTransaccionesFacturaIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
